### ISSUE TITLE
Use cases: data tracker

### ISSUE THREAD

**Issue by cboettig** [cboettig/contentid#16]
@jhpoelen I've created a quick proof-of-principle example of using contenturi + GitHub Actions to run a cron job that 'observes', stores, and registers content at a URL: https://github.com/boettiger-lab/data-tracker

(This particular URL is updated ~ monthly I think, and is an FTP resource which doesn't play nicely with hash-archive.org, but the tracker publishes versioned https -based URLs for the resource)

**Comment by jhpoelen** [comment]
Cool! Are you keeping track of the individual hash calculation events?

**Comment by cboettig** [comment]
yup.  The call to `store()` updates this local registry: https://github.com/boettiger-lab/data-tracker/blob/master/data/registry.tsv.gz (following your words -- `store` must always update a registry, but not vice versa: `register()` never calls `store()`)  

Separately, the URLs created are registered to <hash-archive.org>.   

```r
register(urls, registries="https://hash-archive.org"))
```

**Comment by jhpoelen** [comment]
Nice!

from registry.tsv : 


identifier | source | date
-- | -- | --
hash://sha256/17b81c3c1c4a57e30371eaff008625f407116b38b3d679e547ac8fcbec73e1cb | ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt | 2020-02-21T20:20:35Z
hash://sha256/17b81c3c1c4a57e30371eaff008625f407116b38b3d679e547ac8fcbec73e1cb | data//17/b8/17b81c3c1c4a57e30371eaff008625f407116b38b3d679e547ac8fcbec73e1cb | 2020-02-21T20:20:35Z
hash://sha256/17b81c3c1c4a57e30371eaff008625f407116b38b3d679e547ac8fcbec73e1cb | https://github.com/boettiger-lab/data-tracker/raw/master/data/17/b8/17b81c3c1c4a57e30371eaff008625f407116b38b3d679e547ac8fcbec73e1cb | 2020-02-21T20:29:24Z

suggest to add a uuid column to allow for unambiguous reference to hash generation event. Also, note that the local reference (e.g., ```data//17/b8/17b81...```) is relative and has two forward slashes. Is this intentional?

**Comment by jhpoelen** [comment]
I expected something like: ```file:data/17/b8/....``` and now I wonder: are file: urls allowing relative paths?

**Comment by jhpoelen** [comment]
Cool that you are also registering the registry itself ; )

**Comment by jhpoelen** [comment]
From what I can tell, the registry.tsv.gz contains two registries - a local one (with relative file urls), a remote one, hosted by github.

**Comment by cboettig** [comment]
Re `uuid` column: https://github.com/cboettig/contenturi/issues/5#issuecomment-588612329
(tldr; yeah I should probably add a UUID column)

Re: relative paths and "two registries" -- that's interesting, I hadn't thought of it that way before!  In my brain, this is "one registry" (i.e. it's one file with a specific location), and it's a "local registry" (i.e. can be found on my computer), that happens to register both URLs and local paths.  But this is the first time I've 'published' a registry, and I see your point!  It would perhaps be better to use separate registry.tsv.gz files for, say, the URL sources (which it makes sense to publish) and relative local paths (which we probably shouldn't be publishing).

Part of me wants to view registries as a lot more fluid though -- from a user perspective, for the most part I don't care "where a registry lives" or "what registry an entry came from".  e.g. setting local paths aside for the moment, I could easily have a registry that is a mash up of information from many observers -- i.e. the 'registry' entries for a given URL returned from hash-archive.org combined with a 'registry' of content uris I computed on my own machine.  Currently `query()` quite literally does this.  (i.e. registry entries are essentially atomic facts about the world; RDF triples, and it's not relevant what harddisk or file they sit in.  -- of course my local paths are failing that).  

I think this again highlights we really should answer the questions on #12, #13, #14, and #15 so we're on the same page.  In particular, this issue seems related to the question of is `store("https://example.com")` a valid call, or should `store()` only work with local paths?  (because if you can call `store("https://example.com")`, it seems you should also register the URL.  Or should `store()` be using two separate registries, one for URLs one for local paths?).


(From this discussion I'm now leaning toward the realization that `store` should still take URLs or local paths, but should manage two separate registry files... is that wise?)

**Comment by cboettig** [comment]
Re format for local paths: from my reading of https://en.wikipedia.org/wiki/File_URI_scheme, File URI schemes are absolute paths?

But our discussion closely parallels other standards that use local paths: https://en.wikipedia.org/wiki/BagIt  (i.e. the 'local registry' could clearly be published as a BagIt -- it is in a sense a re-invention of BagIt)

**Comment by cboettig** [comment]
I've updated the data-tracker example to use the `bagit` branch (see PR #17) as a possible sketch of `store` having separate registries for local paths vs url content, as you can now see here: https://github.com/boettiger-lab/data-tracker/tree/master/store

I'm not entirely sure this is the right way to go.  

the `manifest-sha256.txt` is somewhat pointless since the paths are already hashes in this case, but it does generalize nicely since it's an existing standard and the `/ab/cd/abcdef...` paths in the store are I think just a convention.  Now the `registry.tsv.bz2` should technically live inside `data/` or at a different path entirely, since it's not a valid root-level file under BagIt (not that we're actually leveraging BagIt-based tech here so maybe that doesn't matter). 

I can't decide if it bothers me that the`manifest-sha256.txt` file doesn't have a date.  In a way it's nice, since it means we don't update the manifest if the content hasn't changed, but if it has, then I can't really tell what's older (except that more recent hashes will be lower down but that's cheating).  In any event, I think the idea has always been that we'd have separate `prov` functions to associate metadata with content anyway.

**Comment by jhpoelen** [comment]
Cool to hear that you've stumbled across bag-it! 

I have looked at bag-it in the past and found it particularly useful as a way to specify and transfer a potentially large collection of data from location A to location B. However, there doesn't seem to be room for semantics (where did the data come from? how are their related? who made the claim that url X generated hash Y?). 

I can see how a specific collection of content and their associated Preston-like/Prov-O provenance logs (or their "lite" versions) can be expressed in bag-it to provide a trusted (through hash manifests) method to transfer a specific content store or registry from A to B. 

So, as you are hinting, the bag-it can be wrapped around a content store and content registry for the purposes of moving them. And . . . a bag is just a bag and does what it does best: move stuff.

**Comment by cboettig** [comment]
Right, neither our registry (with columns: content `identifier`, `source` url, `date`, and now `uuid`), or the bagit manifest (with essentially just `identifier`, `source`, have any semantics.  `registry.tsv.gz` maps content identifiers to URLs (remote locations), and bagit `manifest-sha256.txt` maps content identifiers to local paths.   (i.e. manifest-sha256.txt effectively contains a content URIs too).  

However, both do seem well suited for a "bring your own semantics" model that can apply semantics directly to content (potentially quite independent of the multiple locations that content can be found; even though those locations).  I think having this separation is quite nice.  (Of course this is a common pattern for data repos, but the magic here is in the advantage of using content hash URIs on both sides).  

So I guess I'm saying I imagine `contenturi` will cover only part of what `preston` does, but that most  use cases would draw on `contenturi` + a second package (say, `prov`, `dcat2`, `schema`, or perhaps a more domain specific metadata model like `EML`, or some combination) to manage the metadata semantics associated with each content identifier.  (that way we also don't need to back a particular horse on the prov / metadata modeling).  Does that make sense?  Or do you think the tasks are so enmeshed that it's unwise to try and an architecture that makes them distinct?

**Comment by cboettig** [comment]
I've updated the README over at the data-tracker example to have a more involved discussion of what it is doing: https://github.com/boettiger-lab/data-tracker.  feedback welcome.  Could become something a vignette / example for the package here.
