### ISSUE TITLE
support queries to SoftwareHeritage

### ISSUE THREAD

**Issue by cboettig** [cboettig/contentid#19]
The SoftwareHeritage Project is archiving all of GitHub, GitLab, [and many other hosts of open source content](https://archive.softwareheritage.org/).  Their API supports querying for content by hash (including sha-256 hash): 

https://docs.softwareheritage.org/devel/swh-web/uri-scheme-browse-content.html

(I'm not quite clear yet when the last crawl was / how frequent the crawls are, but here's some examples): 

Here's the same SHA-256 hash for the classic CO2 data I use as the example:
https://archive.softwareheritage.org/browse/content/sha256:9412325831dab22aeebdd674b6eb53ba6b7bdd04bb99a4dbb21ddff646287e37/

And here's a query for the SHA-256 hash of the README.md of your `rglobi` package: 
https://archive.softwareheritage.org/browse/content/sha256:e3251016573eca693848d060e42cc0563ac99db4cdec1f9bd0a6375ee7a0bd8d/

**Comment by cboettig** [comment]
Actually the API does more than I mentioned above, and I think is worth a close look at all the functions.  https://archive.softwareheritage.org/api/

In particular, you can trigger an archive event; which means that for any content located at a recognized version control provider (GitHub, GitLab, etc), you have a function to 'publish' that content to the store (which is better than waiting for a crawl), and then can request that content back later by the pure sha 256 hash.  

It looks like you can also query by `Origin` (i.e. url) rather than content, or by `Visit` (which is, I a gather, what we call a register() event)  etc.

**Comment by cboettig** [comment]
This is pretty cool:

Software Heritage has indexed all of CRAN, meaning that we have content-identifiers and a permanent store for any package on CRAN. This means that we can grab any specific version of a package published to CRAN, say, `readr` v 1.3.0, by it's hash:

```r
 query_sources("hash://sha256/5d005f8a9b1078ee093d41a48d3b65fb1e03745a0941ac5e58bb4efaf3c4d204")
```

```
                 source
1 https://archive.softwareheritage.org/api/1/content/sha256:5d005f8a9b1078ee093d41a48d3b65fb1e03745a0941ac5e58bb4efaf3c4d204/raw/
2 https://cran.r-project.org/src/contrib/Archive/readr/readr_1.3.0.tar.gz
                 date
1 2020-03-27 20:17:11
2 2020-03-27 20:00:25
```

Note that the first URL is the software heritage archival version, while the second is the link from [CRAN's archive page](https://cran.r-project.org/src/contrib/Archive/readr/) (which I had posted to hash-archive.org), verifying it is the same content.  

In this way, we could install a (cryptographically verified) specific version of any package directly from the Software Heritage Archive.

**Comment by cboettig** [comment]
This is implemented, but just remains to be documented.  I think we should probably have a software heritage vignette that can cover things like:

- Querying content that already exists in the SWH archive (via `query_sources()`)  
- Publishing a permanent archive of data you are using from a GitHub repository (yours or any public repo) using `store_swh()`

I think this 2nd one is a real win relative to readily available / increasingly popular alternatives like using Zenodo's GitHub integration to archive on GitHub release.   

  - no need for authentication, 
  - works even for public repos you don't own 
  - works with GitLab too, (and potentially any `git`, `svn`, or `hg` repo)
  - Creates persistent content-based identifiers to every piece of content
  - calling multiple times doesn't create multiple copies (like the 4 versions of version 2 of Biotime: https://doi.org/10.5281/zenodo.1095627)
  - can use the content identifier directly in scripts
  - cryptographically verifiable


Obviously there are many advantages to submitting to Zenodo (or other data archive) when you need a DOI for citation purposes, want to track downloads, be discoverable in the data repo's search index, etc.  But Zenodo is often used as well to archive things where being independently discoverable and citable isn't the core objective, but merely a bi-product of wanting a persistent storage that can be reliably resolved.  

And of course the nice thing about content identifiers is that these aren't mutually exclusive, we can start by snapshotting our repo in SWH, and later publish it with a DOI and register those links in hash-archive, a local registry, etc and `contenturi` can understand these are the same content.

**Comment by maelle** [comment]
shouldn't the functions related to Software Heritage API live in a dedicated package?

**Comment by cboettig** [comment]
@maelle Thanks, yes, it might be nice to have a complete R package implementation of bindings to the software heritage api, but here we're only using a small subset of that API in a stylized way.

**Comment by cboettig** [comment]
swh bindings are implemented now:

```
history_swh()
sources_swh()
retrieve_swh()
store_swh()
```

`sources_swh()` is used inside `query_sources()` by default, along with hash-archive, so it can discover content by hash from the Software Heritage archive.  

`retrieve_swh` is just a wrapper around `sources_swh()` that returns a url instead of a data.frame (since SWH always returns only a single URL to content). 

`history_swh()` may not be worth keeping as it doesn't conform to the precise schema hash-archive history(), but can be useful in inspecting when a GitHub repo was last snapshot.  

`store_swh()` triggers a snapshot event in SWH.  Arguably this would be better-named (or aliased) as `register_swh()`, since `register()` is a core function that results in an ID being calculated.  (though in this case, SWH is also storing the bits and bytes).
