### ISSUE TITLE
understanding streaming with multiple hashes

### ISSUE THREAD

**Issue by cboettig** [cboettig/contentid#38]
Just trying to wrap my head around how streaming content from URLs into hash functions works, and what the implications are for doing this if I want to compute more than one hash. 

My understanding is that if I do:

```r
openssl::sha256(curl::curl("https://zenodo.org/record/3678928/files/vostok.icecore.co2"))
```

This streams the bits straight through the `sha256` algorithm and discards them, which allows it to execute with very minimal memory use and no disk storage.  

However, if we want to compute multiple hashes for the same object, we don't have a similar mechanism that would allow us to stream the data through multiple algorithms.  We're faced with either downloading to a file or downloading once-per-hash.  The latter will be much slower, the former requires we have sufficient temporary storage, so neither feels ideal...

**Comment by cboettig** [comment]
Wow, @jeroen points out this is technically possible using the internals in `openssl` R package:

https://gist.github.com/jeroen/2087db9eaeac46fc1cd4cb107c7e106b#file-multihash-R

**Comment by jhpoelen** [comment]
Streaming to the rescue! Neat.

**Comment by jeroen** [comment]
I have added a new `multihash` function to the dev version of the openssl pkg.
