### ISSUE TITLE
Suggestion for the first sentence of the README

### ISSUE THREAD

**Issue by maelle** [cboettig/contentid#47]
from "contentid seeks to facilitate reproducible workflows that involve external data files through the use of content identifiers."

to 

"contentid seeks to facilitate reproducible workflows that involve changing external data files, through the use of content identifiers." (adding "changing", and a comma)

**Comment by cboettig** [comment]
Thanks Maelle!  Maybe I need to work on this further though -- I think this workflow is good for files that don't change (i.e. the Vostok example data I use isn't changing).  

Or to put another way, if you have a script that reads in an external file and you want that script to be rock-solid reproducible, you want to be *certain* the input file hasn't changed.  Without this approach, it might get changed "on purpose" (the provider has updated the file at a given URL) or by accident (the URL has gone dark, the data got corrupted on disk, you accidentally overwrote the file, etc).  How can I better express that?

(You can see I'm too long-winded!)

**Comment by maelle** [comment]
Right, and I actually realized "changing" wasn't the point when reading further.

When a one-liner isn't easy to find I like the approach "question? question? this package blabla!" :-)

**Comment by cboettig** [comment]
good idea!  how's this? edits/other suggestions welcome

> writing R scripts that load external data files?  Worried that data might change on you?  Use `contentid` for more robustly reproducible analyses!

**Comment by maelle** [comment]
Yesss! Maybe "on you or your collaborators"?
