### ISSUE TITLE
Intro vignette?

### ISSUE THREAD

**Issue by alexploner** [cboettig/contentid#63]
Dear Carl, 

this is brilliant work, and I almost ignored it when scanning new CRAN packages for lack of a vignette... I see from the source that you do have extensive plans in that direction, but may I suggest that you just copy/adapt the github README as intro-to-contentid in the meantime? It's  very accessible, and should help to spread the good news  to sloppy readers (like myself) at little cost.

**Comment by cboettig** [comment]
thanks!  Copied over via #64 so will be in next release.  

Yup, hope to some more detailed topic-vignettes up eventually as well.
