### ISSUE TITLE
feature request: function to query registries

### ISSUE THREAD

**Issue by joelnitta** [cboettig/contentid#85]
`sources()` tells us about the URLs corresponding to a given contentid and `history_url()` tells us about the contentids corresponding to a given URL, but there is no function that returns the registry where this relationship is documented.

## Requested function
`foo(contentid)` that would return the registry(ies) for that contentid, e.g. `"https://hash-archive.carlboettiger.info/"`

**Comment by cboettig** [comment]
can you describe the use case for this a bit better?  A user can currently achieve this by using a function like `sources()`
 but explicitly naming the registry of interest to see if the ID belongs in that particular registry, e.g.
 
 ```r
sources("hash://sha256/9412325831dab22aeebdd674b6eb53ba6b7bdd04bb99a4dbb21ddff646287e37",
        "https://hash-archive.carlboettiger.info")
 ```
 
Confirms that this ID is  "https://hash-archive.carlboettiger.info" (and further, that  "https://hash-archive.carlboettiger.info" knows of multiple sources for this).  

It should be straight-forward to adapt this to see if the ID is known to other registries.  

 By default / for convenience, these functions search over multiple registries.  From a design perspective, I'm interested in keeping the namespace / API of contentid pretty tight, ideally these functions are good abstractions between IDs and locations such that the user doesn't need to worry about the registry identity (keeping in mind that in many cases, the registry is also the store anyway, e.g. Zenodo, DataONE, Software Heritage, or the local content store).
